version: '3.4'
networks:
  demoapp:
services:
  demoappdb:
    container_name: sqldb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - demoapp

  dotnetcomputersekho:
    image: ${DOCKER_REGISTRY-}dotnetcomputersekho
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:80
    depends_on:
      - demoappdb
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=DemoCSApp
      - DB_SA_PASSWORD=password@12345#
    networks:
      - demoapp
